title: ARX Programming Language
description: A Pascal-inspired, object-oriented programming language with a virtual machine target
url: "https://mootwise-matt.github.io"
baseurl: "/arx-lang"

# GitHub Pages settings
remote_theme: minima